gssoc:approved:
  - ".*"

mentor:PankajSingh34:
  - ".*"

level:beginner:
  - ".*beginner.*"
  - ".*easy.*"
  - ".*simple.*"

level:intermediate:
  - ".*medium.*"
  - ".*intermediate.*"

level:advanced:
  - ".*hard.*"
  - ".*advanced.*"
  - ".*complex.*"

type:bug:
  - ".*bug.*"
  - ".*error.*"
  - ".*fix.*"

type:docs:
  - ".*documentation.*"
  - ".*docs.*"
  - ".*readme.*"

type:feature:
  - ".*feature.*"
  - ".*enhancement.*"
  - ".*add.*"

type:design:
  - ".*ui.*"
  - ".*ux.*"
  - ".*design.*"
